<center>
<h1> Morphological Transformations</h1>
</center>

<center> 
<a> https://docs.opencv.org/4.x/d9/d61/tutorial_py_morphological_ops.html</a>
    </center>


Morphological transformations are simple and powerful ways to change the shape and appearance of objects in an image. They can help us to remove noise, find objects, read barcodes, and more.

## What are Morphological Transformations?
- Morphological transformations are operations that modify the structure of an image based on a given shape or kernel. 
- The kernel is a small matrix that defines the region of interest around each pixel. 
- Depending on the type of operation, the kernel can either add or remove pixels from the image.
---
- There are two basic types of morphological transformations: 
---
- Erosion and Dilation. 
1. Erosion makes the objects in an image smaller by eroding away the boundary pixels. 
2. Dilation makes the objects in an image bigger by adding pixels to the boundary. 

- These operations can be combined to create more complex transformations, such as opening, closing, gradient, top hat, and black hat.

## How to Perform Erosion and Dilation in OpenCV?


- To perform erosion and dilation in OpenCV, we can use the `cv.erode()` and `cv.dilate()` functions. 
- These functions take an input image, a kernel, and a number of iterations as parameters. 
- The kernel can be any shape or size, such as a square, a circle, or a cross. 
- The number of iterations determines how many times the operation is applied to the image.


## Erosion

- Erosion is making the white parts smaller by taking away the pixels near the edges. 
- It is like rubbing the edges of the things with a small square or circle. 
- The small square or circle moves over the picture and changes the pixel in the middle to the smallest value of all the pixels under it. 
- This means that if any pixel under it is black, the middle pixel will also become black. 
- Erosion can be used to remove small white dots or split two things that are touching.

The basic idea of erosion is just like soil erosion only, it erodes away the boundaries of foreground object (Always try to keep foreground in white). So what it does? The kernel slides through the image (as in 2D convolution). A pixel in the original image (either 1 or 0) will be considered 1 only if all the pixels under the kernel is 1, otherwise it is eroded (made to zero).

So what happends is that, all the pixels near boundary will be discarded depending upon the size of kernel. So the thickness or size of the foreground object decreases or simply white region decreases in the image. It is useful for removing small white noises (as we have seen in colorspace chapter), detach two connected objects etc.

In [19]:
import cv2 as cv
import numpy as np

img = cv.imread('Images/morph_input.jpg')
kernel = np.ones((3,3),np.uint8)
erosion = cv.erode(img,kernel,iterations = 3)
cv.imshow('Erosion',erosion)
cv.waitKey(0)
cv.destroyAllWindows()

## Dilation

- Dilation is making the white parts bigger by adding pixels to the edges. 
- It is like stretching the edges of the things with a small square or circle. 
- The small square or circle moves over the picture and changes the pixel in the middle to the biggest value of all the pixels under it. 
- This means that if any pixel under it is white, the middle pixel will also become white. 
- Dilation can be used to fill small holes or gaps in a thing or join broken parts of a thing.

It is just opposite of erosion. Here, a pixel element is '1' if at least one pixel under the kernel is '1'. So it increases the white region in the image or size of foreground object increases. Normally, in cases like noise removal, erosion is followed by dilation. 

Because, erosion removes white noises, but it also shrinks our object. So we dilate it. Since noise is gone, they won't come back, but our object area increases. It is also useful in joining broken parts of an object.

In [20]:
import cv2 as cv
import numpy as np

img = cv.imread('Images/morph_input.jpg')

kernel = np.ones((3,3),np.uint8)
# kernel = cv.getStructuringElement(cv.MORPH_ELLIPSE,(5,5))
erosion = cv.erode(img,kernel,iterations = 2)

cv.imshow('Erosion',erosion)
cv.waitKey(0)
cv.destroyAllWindows()


## How to Perform Other Morphological Operations in OpenCV?

- Opening and closing are two common morphological operations that combine erosion and dilation. 

 1. Opening is erosion followed by dilation. It can be used to remove small noise from an image while preserving the shape of the objects. 
 ---
2. Closing is dilation followed by erosion. It can be used to fill small holes or gaps in an image while preserving the shape of the objects.

- To perform opening and closing in `OpenCV`, we can use the `cv.morphologyEx()` function with `cv.MORPH_OPEN` and `cv.MORPH_CLOSE` parameters. 
- This function takes an input image, a kernel, and a type of operation as parameters.

In [ ]:
import cv2 as cv 
import numpy as np 

# img = cv.imread('Images/morph_input.jpg')
img = cv.imread('Images\j.png')
kernel = np.ones((3,3) , np.uint8)

opening = cv.morphologyEx(img ,  cv.MORPH_OPEN , kernel)

cv.imshow('Image' , img)
cv.imshow('img' , opening)
cv.waitKey(0)
cv.destroyAllWindows()


**We can see that the noise has been removed and the img is still clear.**

### We can use the same kernel and closing operation to fill the gaps 

In [33]:
import cv2 as cv 
import numpy as np 

img = cv.imread('Images\j.png')

kernel = np.ones((3,3) , np.uint8)

opening = cv.morphologyEx(img ,  cv.MORPH_CLOSE , kernel)

cv.imshow('Image' , img)
cv.imshow('img' , opening)
cv.waitKey(0)
cv.destroyAllWindows()


## How to Perform Other Morphological Operations

Besides opening and closing, there are some other morphological operations that we can perform using the cv.morphologyEx() function. These operations are:

1. **Gradient**: 
- The difference between dilation and erosion. It can be used to highlight the edges of the objects in an image.

In [1]:
import cv2 as cv 
import numpy as np 

img = cv.imread('Images\j.png')

kernel = np.ones((3,3) , np.uint8)

Gradient = cv.morphologyEx(img ,  cv.MORPH_GRADIENT , kernel)

cv.imshow('Image' , img)
cv.imshow('Gradient' , Gradient)
cv.waitKey(0)
cv.destroyAllWindows()


#### We can see that the edges of the Image are more visible.



2. **Top Hat**: 
- The difference between the input image and its opening. It can be used to extract bright spots from a dark background.
---

In [2]:
import cv2 as cv 
import numpy as np 

img = cv.imread('Images\j.png')

kernel = np.ones((3,3) , np.uint8)

TOPHAT = cv.morphologyEx(img ,  cv.MORPH_TOPHAT , kernel)

cv.imshow('Image' , img)
cv.imshow('TOPHAT' , TOPHAT)
cv.waitKey(0)
cv.destroyAllWindows()


#### We can see that the bright spots are more visible.


3. **Black Hat**: 
- The difference between the input image and its closing. It can be used to extract dark spots from a bright background.

In [5]:
import cv2 as cv 
import numpy as np 

img = cv.imread('Images\j.png')

kernel = np.ones((3,3) , np.uint8)

BLACKHAT = cv.morphologyEx(img ,  cv.MORPH_BLACKHAT , kernel)

cv.imshow('Image' , img)
cv.imshow('BLACKHAT' , BLACKHAT)
cv.waitKey(0)
cv.destroyAllWindows()


#### We can see that the dark spots are more visible.

## More about Kernel's

####  A kernel is a small matrix that defines the shape and size of the region that we want to modify in an image. 
#### For example, a 3x3 kernel looks like this:
|1 1 1|

|1 1 1|

|1 1 1|

- We can use different kernels to perform different morphological operations, such as erosion, dilation, opening, closing, etc. 
- For example, if we want to **erode** an image, we use a kernel to scan through the image and check if all the pixels under the kernel are 1. 
- If yes, we keep the origin pixel as 1. 
- If no, we change the origin pixel to 0. 
- This way, we can shrink the objects in the image by removing the boundary pixels.

If we want to **dilate** an image, we use a kernel to scan through the image and check if any of the pixels under the kernel are 1. If yes, we change the origin pixel to 1. If no, we keep the origin pixel as 0. This way, we can enlarge the objects in the image by adding pixels to the boundary.

We can also use different shapes and sizes of kernels to achieve different effects. For example, we can use a circular kernel instead of a square one, or we can use a larger kernel to affect more pixels. 

In [ ]:
# Rectangular Kernel
>>> cv.getStructuringElement(cv.MORPH_RECT,(5,5))
array([[1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1]], dtype=uint8)


# Elliptical Kernel
>>> cv.getStructuringElement(cv.MORPH_ELLIPSE,(5,5))
array([[0, 0, 1, 0, 0],
 [1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1],
 [0, 0, 1, 0, 0]], dtype=uint8)


# Cross-shaped Kernel
>>> cv.getStructuringElement(cv.MORPH_CROSS,(5,5))
array([[0, 0, 1, 0, 0],
 [0, 0, 1, 0, 0],
 [1, 1, 1, 1, 1],
 [0, 0, 1, 0, 0],
 [0, 0, 1, 0, 0]], dtype=uint8)

### A square kernel: 
#### This kernel has all elements equal to one and has a square shape. For example, a 3x3 square kernel is:

|1 1 1|

|1 1 1|

|1 1 1|

---
### A circular kernel: 
####  This kernel has elements equal to one only if they are inside a circle and zero otherwise. For example, a 3x3 circular kernel is:

|0 1 0|

|1 1 1|

|0 1 0|

---

### A cross-shaped kernel: 
#### This kernel has elements equal to one only if they are on the horizontal or vertical axis and zero otherwise. For example, a 3x3 cross-shaped kernel is:

|0 1 0|

|1 1 1|

|0 1 0|

---

### A custom kernel: 
##### This kernel can have any shape and values that suit the specific problem. For example, a custom kernel that can detect horizontal lines is:

|-1 -1 -1|

| 2  2  2|

|-1 -1 1-|

---

 You can create your own kernels using NumPy’s functions such as `np.ones`, `np.zeros`, `np.eye`, etc. 
 
 You can also use OpenCV’s function `cv2.getStructuringElement` to create predefined kernels such as square, circular, or elliptical.

#### There are three shapes of kernels that can be created using cv2.getStructuringElement:

1. Rectangular: cv2.MORPH_RECT
2. Cross-shaped: cv2.MORPH_CROSS
3. Elliptical: cv2.MORPH_ELLIPSE

The size of the kernel is given by a tuple of two integers, such as (3, 3) or (5, 5). The larger the size, the more effect the morphological operation will have on the image.

#### For example, to create a 3x3 rectangular kernel, we can use:

**`kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))`**
This will return a matrix like this:

|1 1 1|

|1 1 1|

|1 1 1|


#### To create a 3 X 3 cross-shaped kernel, we can use:
    
**`kernel = cv2.getStructuringElement(cv2.MORPH_CROSS, (5, 5))`**

This will return a matrix like this:

|0 1 0|

|1 1 1|

|0 1 0|


#### To create a 5x5 elliptical kernel, we can use:

**`kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))`**


This will return a matrix like this:
|0 1 0 0 0 |

|0 1 1 1 0 |

|1 1 1 1 1 |

|0 1 1 1 0 |

|0 0 1 0 0 |

Once we have the kernel, we can use it for different morphological operations, such as:

1. Erosion: 
- This operation shrinks the white regions in the image by removing the pixels near the boundaries. It is like eroding the edges of the objects with the kernel. The kernel slides over the image and replaces the pixel at its center with the minimum value of all the pixels under the kernel. This means that if any pixel under the kernel is zero (black), the center pixel will also become zero. Erosion can be used to remove small white noises or detach two connected objects.

---

2. Dilation: 
- This operation enlarges the white regions in the image by adding pixels to the boundaries. It is like dilating the edges of the objects with the kernel. The kernel slides over the image and replaces the pixel at its center with the maximum value of all the pixels under the kernel. This means that if any pixel under the kernel is one (white), the center pixel will also become one. Dilation can be used to fill small holes or gaps in an object or join broken parts of an object.

---
3. Opening: 
- This operation is a combination of erosion followed by dilation. It is useful for removing small objects or noises from an image while preserving the shape and size of larger objects.

---
4. Closing: 
- This operation is a combination of dilation followed by erosion. It is useful for filling small holes or gaps inside an object or joining small cracks or breaks in an object.

---
5. Gradient: 
- This operation is the difference between dilation and erosion of an image. It highlights the edges or boundaries of an object in an image.
---
6. Top hat: 
- This operation is the difference between an image and its opening. It reveals bright regions on a dark background that are smaller than the kernel.

---
7. Black hat: 
- This operation is the difference between an image and its closing. It reveals dark regions on a bright background that are smaller than the kernel.

----
You can use `cv2.morphologyEx` function to apply these operations to an image using a given kernel.

##### For example, to apply opening to an image using a rectangular kernel, we can use:

`kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5,5))`


`opening = cv2.morphologyEx(image, cv2.MORPH_OPEN, kernel)`